Simplify userscripts source template
IITC-CE/ingress-intel-total-conversion pull request #229
Opened 2019-07-30 10:17 UTC by johnd0e

Get rid of these substitutions:
- `@@METAINFO@@`
- `@@PLUGINSTART@@`
- `@@PLUGINEND@@`
- `.@@DATETIMEVERSION@@`
- `[@@BUILDNAME@@-@@BUILDDATE@@]`

Sources are tidier without that ugly macros.

2019-07-30 10:19 UTC, johnd0e commented
This early draft created to start discussion.

Currently demo only, for single plugin.
Build script still need to be enhanced.

2019-08-06 21:40 UTC, modos189 commented on build.py
> +if os.path.isfile('./localbuildsettings.py'):
If file is missing, there will be an exception. Not great, not terrible.

BTW, we can use:
```
# load option local settings file and default build
try:
    from localbuildsettings import buildSettings as localBuildSettings, defaultBuild
    buildSettings.update(localBuildSettings)
except ImportError:
    localBuildSettings = {}
    defaultBuild = None
```

2019-08-13 16:08 UTC, johnd0e commented
I am also going to enhance build script to be able to build single plugin (even 3rd-party).

2019-10-25 18:23 UTC, modos189 submitted a review, later dismissed
It's pretty cool on the whole. I left a few questions in the comments

2019-10-25 18:23 UTC, modos189 commented on code/boot.js
> +@include_raw:external/autolink-min.js@
Maybe we should add quotes, make a string?

2019-10-25 18:23 UTC, modos189 commented on plugins/debug-raw-portal-data.user.js
>  // @id             iitc-plugin-raw-portal-data
Did you leave your id here on purpose, or did you forget to remove it?

2019-10-25 18:23 UTC, modos189 commented on plugins/periodic-refresh.user.js
>  // @id             iitc-plugin-periodic-refresh
This is probably where you forgot to remove ID

2019-10-25 18:23 UTC, modos189 commented on total-conversion-build.js
BTW, maybe we should move this file to `code` folder?

2019-10-25 18:23 UTC, modos189 commented on plugins/fix-china-map-offset.user.js
> +﻿// @id             iitc-plugin-fix-china-map-offset
again

2019-10-25 18:23 UTC, modos189 commented on build_plugin.py
> +    template = r"'@(\w+)(?::([0-9a-zA-Z_./-]+))?@'"
Ooh. Uh...)
At least add a comment, please, that it's for finding `@type:string@` tags

2019-10-25 18:23 UTC, modos189 commented on build_plugin.py
> +    return '\n'.join(meta), is_plugin
Please add blank lines, everything is now merging into a solid block

2019-10-25 18:23 UTC, modos189 commented on plugins/basemap-gaode.user.js
> +﻿// @id             iitc-plugin-basemap-gaode
id?

2019-10-25 18:23 UTC, modos189 commented on plugins/basemap-kartverket.user.js
> +﻿// @id             iitc-plugin-basemap-kartverket
id?

2019-10-25 18:23 UTC, modos189 commented on plugins/link-show-direction.user.js
>  // @id             iitc-plugin-link-show-direction
id?

2019-11-29 22:03 UTC, modos189 requested changes
Good job!

2019-11-29 22:03 UTC, modos189 commented on plugins/bookmarks.css
> +	background-image:url(images/bookmarks-img.png);
Should we use `@include_img` here?

2019-11-29 22:09 UTC, johnd0e commented on plugins/bookmarks.css
> +	background-image:url(images/bookmarks-img.png);
No, that is handled in another way.
Urls in CSS are easy to extract with regexp, so no need for special templates.

2019-11-29 22:16 UTC, modos189 commented on plugins/bookmarks.css
> +	background-image:url(images/bookmarks-img.png);
Ok

2019-11-29 22:16 UTC, modos189 approved these changes

2019-12-05 11:03 UTC, merged