Fly-link update to 0.3.0
IITC-CE/ingress-intel-total-conversion pull request #310
Opened 2020-01-14 16:05 UTC by Fly33

+ region selection with the polygon draw tool
+ exclusion of portals with the marker draw tool
+ steady drawing (portals is not excluded from the drawing if they are
moved out of boundaries)

2020-01-14 21:51 UTC, modos189 commented
Looks great. I see no obstacles to merger after the corrective release that will be released the other day.

2020-01-23 16:14 UTC, johnd0e commented
@Fly33 
Could you comment ideas if #203?
Would it be hard to implement?

2020-07-16 10:50 UTC, modos189 requested changes
New version of Leaflet uses the keyword *interactive*. Please do not return outdated *clickable*

2020-07-16 10:50 UTC, modos189 commented on plugins/fly-links.js
> +      clickable: false,
```suggestion
      interactive: false,
```

2020-07-16 10:50 UTC, modos189 commented on plugins/fly-links.js
> +      clickable: false,
```suggestion
      interactive: false,
```

2020-12-16 17:48 UTC, modos189 approved these changes

2020-12-23 22:38 UTC, merged