[privacy-plugin] fix: privacy control is at the top of the page while active
IITC-CE/ingress-intel-total-conversion pull request #427
Opened 2020-12-31 10:00 UTC by le-jeu

fix #426 

also, use #chatcontrol class and css to control the chat toggle shape without changing the toggle class.

2021-03-10 10:31 UTC, johnd0e approved these changes

2021-03-10 15:55 UTC, MysticJay requested changes
The changes return old functionality.
But shouldn't the arrow point down after maximizing?

2021-03-10 16:57 UTC, le-jeu commented
> The changes return old functionality.
> But shouldn't the arrow point down after maximizing?

![image](https://user-images.githubusercontent.com/64744459/110666700-db255a80-81c9-11eb-9d80-9b6fce1f8400.png)

2021-03-10 17:01 UTC, MysticJay approved these changes

2021-03-16 07:47 UTC, modos189 approved these changes

2021-03-16 07:49 UTC, merged