portal-history: separate styles
IITC-CE/ingress-intel-total-conversion pull request #441
Opened 2021-02-14 16:20 UTC by johnd0e

Separate style for every included here highlighter.
Reason for refactoring: now any style may be overridden (inline, or in separate plugin) without touching main logic.

2021-02-14 17:17 UTC, MysticJay commented
The code is complicated without need.
At two places a new function gets inserted that only call one global function.
The construction of the styles from various parts is complex and not easy to maintain.

Create direct named style-objects that hold all wanted properties
and use them directly in `data. portal.setStyle(<name of style>)`

2021-02-15 18:07 UTC, johnd0e commented
not visited has a bug now: we need to check !visited first, then !captured.
Will fix tomorrow.

2021-02-18 19:25 UTC, modos189 requested changes

2021-02-18 19:25 UTC, modos189 commented on plugins/highlight-portal-history.js
> +function inherit (parentName, childNames) {
```suggestion
// Creating styles based on a given template
function inherit (parentName, childNames) {
```

2021-02-18 19:25 UTC, modos189 commented on plugins/highlight-portal-history.js
> +    styles[name] = L.extend(L.Util.create(styles[parentName]), styles[name]);
```suggestion
    // Extension of _styles_ with a new _name_ object, created based on _parentName_ object.
    styles[name] = L.extend(L.Util.create(styles[parentName]), styles[name]);
```

2021-02-19 11:29 UTC, modos189 approved these changes

2021-02-19 16:29 UTC, merged