chat: fix public/faction not cleared on move
IITC-CE/ingress-intel-total-conversion pull request #454
Opened 2021-03-11 20:22 UTC by le-jeu

fix #417

2021-03-12 11:40 UTC, johnd0e requested changes
Nice catch!
I see this in current code:
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/2daad393c75f45e9f121136c4717d4dec51fca4f/core/code/chat.js#L73
But it was not used anywhere before your patch.

I have a couple of minor style suggestions, feel free to decide yourself whether to accept suggestions or not.

2021-03-12 11:40 UTC, johnd0e commented on core/code/chat.js
> +  $('#chatfaction').data('needsClearing', null);
```suggestion
  if (!data.result.length && !$('#chatfaction').data('needsClearing')) {
    return;
  }
  $('#chatfaction').data('needsClearing', null);
```

2021-03-12 11:40 UTC, johnd0e commented on core/code/chat.js
> +  $('#chatall').data('needsClearing', null);
```suggestion
  if (!data.result.length && !$('#chatall').data('needsClearing')) {
    return;
  }
  $('#chatall').data('needsClearing', null);
```

2021-03-12 14:10 UTC, le-jeu commented on core/code/chat.js
> +  $('#chatfaction').data('needsClearing', null);
```suggestion
  if (!data.result.length && !$('#chatfaction').data('needsClearing')) {
    // no new data and current data in chat._faction.data is already rendered
    return;
  }

  $('#chatfaction').data('needsClearing', null);
```

2021-03-12 14:10 UTC, le-jeu commented on core/code/chat.js
> +  $('#chatall').data('needsClearing', null);
```suggestion
  if (!data.result.length && !$('#chatall').data('needsClearing')) {
    // no new data and current data in chat._public.data is already rendered
    return;
  }

  $('#chatall').data('needsClearing', null);
```

2021-03-14 11:14 UTC, johnd0e approved these changes

2021-03-15 05:42 UTC, modos189 approved these changes

2021-03-15 08:11 UTC, merged