Multi-Line-Headers
IITC-CE/ingress-intel-total-conversion pull request #494
Opened 2021-04-29 15:20 UTC by MysticJay

build_plugin.py

Purpose: concatenate lines to avoid long headers, e.g. for Description.

Usecase: Long lines in the sources trigger eslint and reduce readability. 
As *monkey has no trick to handle multi-line headers we need to re-join these during build-process

How to use: This change will concatenate the next (comment) line to the previous header. Indentation is optional.
```
// @keyword line 1
//      line 2
//      line 3
// @keyword2 text
```
becomes
```
// @keyword line 1 line 2 line 3
// @keyword2
```
during build-process.

2021-05-09 14:23 UTC, modos189 commented
Maybe it only makes sense to use this for the description tag? The value of the other tags is always short enough.

2021-06-10 13:42 UTC, McBen commented
> Maybe it only makes sense to use this for the description tag? The value of the other tags is always short enough.

Sure. But does it do any harm? And why creating a special case for only one tag?

2021-06-12 13:20 UTC, johnd0e commented
I feel #510 slightly more in line with current code style

2021-06-13 09:14 UTC, le-jeu commented
Third suggestion, repeat the keyword to append

    // @description Foo, contact
    // @description @bar on Twitter

2021-06-13 09:20 UTC, johnd0e commented
@le-jeu Why? Is that supported by any userscript manager?

2021-06-13 09:26 UTC, MysticJay commented
@le-jeu that was my initial, but rejected proposal

2021-06-13 09:27 UTC, MysticJay commented
@johnd0e inly before the build

2021-07-01 14:48 UTC, modos189 requested changes
Good idea, but let's use PR #510 with an alternative implementation that gets rid of regex and looks better in our build system

2021-07-04 10:50 UTC, closed without merging