Machina Player
IITC-CE/ingress-intel-total-conversion pull request #629
Opened 2023-05-14 19:42 UTC by McBen

Machina is now included in chat log.
This leads to some minor problems like chat format and player icons in player-tracker

This PR 
a) adds the neutral chat names
![grafik](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/29117/b74ff41e-ddab-46a4-8910-86230b952507)
white because it's reported as "neutral" and not as MAC.

b) ignore neutral players in player-tracker plugin

2023-05-15 15:39 UTC, McBen commented
7219019 added a new plugin for machina tracking (show markers instead of the path)

2023-05-17 11:06 UTC, McBen commented
Example of the new plugin:
![grafik](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/29117/315868c2-bb03-469e-9be1-63806d0224de)

2023-05-21 13:20 UTC, xscreach requested changes
Small clean up required, see commented lines

2023-05-21 13:20 UTC, xscreach commented on plugins/player-activity-tracker.js
> +    if (!plrname || !lat || !lng || !id || skipThisMessage || json[2].plext.team === 'NEUTRAL') return true;
Rather use `teamStringToId(...team) === window.TEAM_NONE`

2023-05-21 13:20 UTC, xscreach commented on plugins/machina_tracker.user.js
> +    if (!plrname || !lat || !lng || !id || skipThisMessage || json[2].plext.team !== 'NEUTRAL') return true;
Rather use `teamStringToId(...team) !== window.TEAM_NONE`

2023-05-21 13:20 UTC, xscreach commented on core/code/chat.js
> +/* global TEAM_TO_CSS */
These are defined under window. We should imho rather use e.g. `window.teamToStringId` than keep defining these in files again

2023-05-30 07:39 UTC, closed without merging