Update intel link to match stock.
IITC-CE/ingress-intel-total-conversion pull request #723
Opened 2024-03-30 21:21 UTC by nexushoratio

It looks like when `/intel` was removed with e5fe5d8fe, stock was not adding the string to the URL.  Currently it does in both the web and scanner apps.

Closes #684.

2024-03-31 02:26 UTC, xscreach requested changes
This is something niantic didn't do properly... 
We know they won't fix it but do we really want the same "bug" in iitc?
No need to argue,  just asking 😉🤷‍♂️

2024-03-31 04:23 UTC, nexushoratio commented
> This is something niantic didn't do properly... We know they won't fix it but do we really want the same "bug" in iitc? No need to argue, just asking 😉🤷‍♂️

While annoying, repeating strings in the hostname and path is not uncommon, and I wouldn't consider it a bug.

Tabs I have open now that do this:
mail.google.com/mail
calendar.google.com/calendar

The fact both of those are Google is not surprising.  They've always been inconsistent about which way they want to go (which probably bled over into Niantic, particularly since maps.google.com/maps was a thing).

2024-03-31 08:20 UTC, xscreach commented
> > This is something niantic didn't do properly... We know they won't fix it but do we really want the same "bug" in iitc? No need to argue, just asking 😉🤷‍♂️
> 
> While annoying, repeating strings in the hostname and path is not uncommon, and I wouldn't consider it a bug.
> 
> Tabs I have open now that do this:
> mail.google.com/mail
> calendar.google.com/calendar
> 
> The fact both of those are Google is not surprising.  They've always been inconsistent about which way they want to go (which probably bled over into Niantic, particularly since maps.google.com/maps was a thing).

Niantic changed from something.ingress.com/intel to intel.ingress.com without context path. This is clearly remained after this change and is clearly a bug or smth they didn't finish. Period.
Last month some old urls stoped working even though niantic supported them for so long.
I just don't want be changing this again when nia finds some people to work on ingress (haha)

2024-04-01 07:22 UTC, modos189 commented
I agree with @xscreach that most likely /intel is an outdated url and at some point Niantic will finally update the url by making the default url without /intel 
For the same reason this change was made to commit https://github.com/IITC-CE/ingress-intel-total-conversion/commit/e5fe5d8feef0ccd9130b2811a54fceb17c15ccc7

2024-04-01 16:19 UTC, nexushoratio commented
They are just as likely to someday require `/intel` as they are to do away with it.

Meanwhile, their official software (both web and scanner) includes it.

And IITC includes it when it generates a deep (scanner) link.

So, this change removes an unnecessary difference between stock and IITC.

2024-04-09 16:39 UTC, nexushoratio commented
Just checking to see if this has any hope of moving forward, or if I should just withdraw it.

2024-04-09 19:06 UTC, xscreach commented
We can keep discussing this for years... and fiddling with it back and forth..or just wait for niantic to do something that would need an update here and change it then 😉

2024-04-09 20:09 UTC, closed without merging